### ISSUE TITLE
The url of the graph cmdlet Invoke-MgInvalidateUserRefreshToken is incomplete hence a 404 error.

### ISSUE THREAD

**Issue by msewaweru** [microsoft/AzureAD-to-MSGraph#9]
@FriedrichWeinmann - From the index.md file the url for this cmdlet has a missing part.

**Comment by FriedrichWeinmann** [comment]
Thanks for noticing!
Turns out target command resolution failed when resolving a graph command that only existed in the beta version.
I've updated the build script to switch to beta and try again if there is no such command in v1.0 and generated a new set of docs.

**Comment by msewaweru** [comment]
Thanks @FriedrichWeinmann for the prompt action.  I have rechecked and it's ok now.
